/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'SenseMsg'
 * message type.
 */

public class SenseMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 10;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 1;

    /** Create a new SenseMsg of size 10. */
    public SenseMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new SenseMsg of the given data_length. */
    public SenseMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SenseMsg with the given data_length
     * and base offset.
     */
    public SenseMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SenseMsg using the given byte array
     * as backing store.
     */
    public SenseMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SenseMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public SenseMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SenseMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public SenseMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SenseMsg embedded in the given message
     * at the given base offset.
     */
    public SenseMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SenseMsg embedded in the given message
     * at the given base offset and length.
     */
    public SenseMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <SenseMsg> \n";
      try {
        s += "  [sender_id=0x"+Long.toHexString(get_sender_id())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [cnt=0x"+Long.toHexString(get_cnt())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [val=0x"+Long.toHexString(get_val())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [fwd_id=0x"+Long.toHexString(get_fwd_id())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [rec_id=0x"+Long.toHexString(get_rec_id())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: sender_id
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'sender_id' is signed (false).
     */
    public static boolean isSigned_sender_id() {
        return false;
    }

    /**
     * Return whether the field 'sender_id' is an array (false).
     */
    public static boolean isArray_sender_id() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'sender_id'
     */
    public static int offset_sender_id() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'sender_id'
     */
    public static int offsetBits_sender_id() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'sender_id'
     */
    public int get_sender_id() {
        return (int)getUIntBEElement(offsetBits_sender_id(), 16);
    }

    /**
     * Set the value of the field 'sender_id'
     */
    public void set_sender_id(int value) {
        setUIntBEElement(offsetBits_sender_id(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'sender_id'
     */
    public static int size_sender_id() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'sender_id'
     */
    public static int sizeBits_sender_id() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: cnt
    //   Field type: int, unsigned
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'cnt' is signed (false).
     */
    public static boolean isSigned_cnt() {
        return false;
    }

    /**
     * Return whether the field 'cnt' is an array (false).
     */
    public static boolean isArray_cnt() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'cnt'
     */
    public static int offset_cnt() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'cnt'
     */
    public static int offsetBits_cnt() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'cnt'
     */
    public int get_cnt() {
        return (int)getUIntBEElement(offsetBits_cnt(), 16);
    }

    /**
     * Set the value of the field 'cnt'
     */
    public void set_cnt(int value) {
        setUIntBEElement(offsetBits_cnt(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'cnt'
     */
    public static int size_cnt() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'cnt'
     */
    public static int sizeBits_cnt() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: val
    //   Field type: int, unsigned
    //   Offset (bits): 32
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'val' is signed (false).
     */
    public static boolean isSigned_val() {
        return false;
    }

    /**
     * Return whether the field 'val' is an array (false).
     */
    public static boolean isArray_val() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'val'
     */
    public static int offset_val() {
        return (32 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'val'
     */
    public static int offsetBits_val() {
        return 32;
    }

    /**
     * Return the value (as a int) of the field 'val'
     */
    public int get_val() {
        return (int)getUIntBEElement(offsetBits_val(), 16);
    }

    /**
     * Set the value of the field 'val'
     */
    public void set_val(int value) {
        setUIntBEElement(offsetBits_val(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'val'
     */
    public static int size_val() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'val'
     */
    public static int sizeBits_val() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: fwd_id
    //   Field type: int, unsigned
    //   Offset (bits): 48
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'fwd_id' is signed (false).
     */
    public static boolean isSigned_fwd_id() {
        return false;
    }

    /**
     * Return whether the field 'fwd_id' is an array (false).
     */
    public static boolean isArray_fwd_id() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'fwd_id'
     */
    public static int offset_fwd_id() {
        return (48 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'fwd_id'
     */
    public static int offsetBits_fwd_id() {
        return 48;
    }

    /**
     * Return the value (as a int) of the field 'fwd_id'
     */
    public int get_fwd_id() {
        return (int)getUIntBEElement(offsetBits_fwd_id(), 16);
    }

    /**
     * Set the value of the field 'fwd_id'
     */
    public void set_fwd_id(int value) {
        setUIntBEElement(offsetBits_fwd_id(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'fwd_id'
     */
    public static int size_fwd_id() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'fwd_id'
     */
    public static int sizeBits_fwd_id() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: rec_id
    //   Field type: int, unsigned
    //   Offset (bits): 64
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'rec_id' is signed (false).
     */
    public static boolean isSigned_rec_id() {
        return false;
    }

    /**
     * Return whether the field 'rec_id' is an array (false).
     */
    public static boolean isArray_rec_id() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'rec_id'
     */
    public static int offset_rec_id() {
        return (64 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'rec_id'
     */
    public static int offsetBits_rec_id() {
        return 64;
    }

    /**
     * Return the value (as a int) of the field 'rec_id'
     */
    public int get_rec_id() {
        return (int)getUIntBEElement(offsetBits_rec_id(), 16);
    }

    /**
     * Set the value of the field 'rec_id'
     */
    public void set_rec_id(int value) {
        setUIntBEElement(offsetBits_rec_id(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'rec_id'
     */
    public static int size_rec_id() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'rec_id'
     */
    public static int sizeBits_rec_id() {
        return 16;
    }

}
