#!/bin/bash
# A simple script to set up a git repository
# for 1428 Honors
# Written by Jared Wallace

FIRST_LAB_DIR=Lab1
E_XCD=86

echo -n "Please enter the name of the directory you want to store the lab files in "
read BASE_DIR
BASE_DIR=$HOME/$BASE_DIR
if [ ! -d "$BASE_DIR" ]
then
    mkdir $BASE_DIR
fi

cd $BASE_DIR || {
    echo "Could not switch to lab directory, quitting" >&2
    exit $E_XCD
}
if [ ! -d "Lab1" ]
then
    mkdir Lab1
fi

cd Lab1 || {
    echo "Could not switch to lab1 directory, quitting" >&2
    exit $E_XCD
}
git init
touch README.md
git add README.md
echo -n "Please enter your full name: "
read NAME
echo -n "Please enter your preferred email address: "
read EMAIL
git config --global user.name "$NAME"
git config --global user.email $EMAIL
git commit -m 'Initial commit, autogenerated'
echo -e "\n"
echo -n "Please enter your netid: "
read NET_ID
git remote add origin git@gitlab.cs.txstate.edu:$NET_ID/Lab1.git
ssh-keygen -t rsa -N "" -f $HOME/.ssh/id_rsb
echo -e "\n"
echo -e "\n"
cat $HOME/.ssh/id_rsb.pub
echo -e "\n"
echo -e "\n"
echo "This is your new SSH key."
echo "Please wait for instructions!"
read trash

git push origin master
