#!/bin/bash
# A simple script to set up a git repository
# for 1428 Honors
# Written by Jared Wallace

# This script is intended to be run only one time,
# for initial setup. We name the directories accordingly
FIRST_LAB_DIR=Lab1
E_XCD=86

echo -n "Please enter the name of the directory you want to store ALL of your lab files in "
read BASE_DIR
BASE_DIR=$HOME/$BASE_DIR
if [ ! -d "$BASE_DIR" ]
then
    mkdir $BASE_DIR
fi

cd $BASE_DIR || {
    echo "Could not switch to lab directory, quitting" >&2
    exit $E_XCD
}

# We just call the first repo directory Lab1
# by default
if [ ! -d "Lab1" ]
then
    mkdir Lab1
fi

cd Lab1 || {
    echo "Could not switch to lab1 directory, quitting" >&2
    exit $E_XCD
}

git init
touch README.md
git add README.md
echo -n "Please enter your full name: "
read NAME
echo -n "Please enter your preferred email address: "
read EMAIL
git config --global user.name "$NAME"
git config --global user.email $EMAIL
git commit -m 'Initial commit, autogenerated'
echo -e "\n"
echo -n "Please enter your netid: "
read NET_ID
git remote add origin git@gitlab.cs.txstate.edu:$NET_ID/lab1.git
# Now let's see if they have an ssh key yet
KEY=$HOME/.ssh/id_rsa

if [ ! -f $KEY ]
then
    ssh-keygen -t rsa -N "" -f $HOME/.ssh/id_rsa
else
    echo "Found existing ssh key, using..."
fi

echo -e "\n"
echo -e "\n"
cat $HOME/.ssh/id_rsa.pub
echo -e "\n"
echo -e "\n"
echo "This is your SSH key."
echo "Please wait for instructions!"
# Here the lab instructor needs to guide the students through
# creating their remote repository. It MUST be named "Lab1"
# or the script will not work. When finished, direct the
# student to press enter
read trash

git push -u origin master
